### ISSUE TITLE
Change colours for key press popup

### ISSUE THREAD

**Issue by smithjoelt** [gazlaws-dev/codeboard#14]

**Comment by smithjoelt** [comment]
case in point. which key is being triggered? who knows?

**Comment by LordKrishna91** [comment]
There is an indicator. it's just not quite visible. On some themes it may be less visible e.g pure black it's less visible.


![Material dark keypress screenshot]

![Key press on Material dark codeboard theme](http://i.imgur.com/Zrhnvo0.jpg)

**Comment by theintel** [comment]
The border colour of the pop-up letter should be white for dark theme and vice versa.

**Comment by LordKrishna91** [comment]
It's not the border color but the entire click indicator which should be easily recognizable like AOSP, gboard etc  they use grey colour for simple click recognization. this app should use different Colors for dark and pure black themes .

**Comment by gazlaws-dev** [comment]
I did plan to change that, but I'm busy with college. If anyone wants to work on it, let me know.
