### ISSUE TITLE
Enter does not work in decoder & 920 text editor app.

### ISSUE THREAD

**Issue by LordKrishna91** [gazlaws-dev/codeboard#15]
hi, using codeboard from play store the enter key does not work in the apps decoder & 920 text editor but other keyboards responds to this key in the respective apps

**Comment by theintel** [comment]
I checked it. Its strange that the Enter key doesn't work only in Dcoder.

You should submit an issue on Dcoder's repository as well.

**Comment by LordKrishna91** [comment]
Decoder is not an open source app; 
I contacted the support of that app they will see what can be done but their app uses generic textedit component of Android

**Comment by LordKrishna91** [comment]
Continue: which is built on top of it.
They said to contact codeboard app developer but they will try if this can be solved on their end but the issue seems from this side of the app.

**Comment by LordKrishna91** [comment]
Update: Enter key does not work in 920 text editor too. The problem is Codeboard keyboard app.

**Comment by theintel** [comment]
coding without Enter is 😵
We expect a quick fix.

**Comment by LordKrishna91** [comment]
The newest version of the app fixes this issue
