### ISSUE TITLE
Using Shft+ctrl does not let you output a capital letter

### ISSUE THREAD

**Issue by ghost** [gazlaws-dev/codeboard#16]
Hi, using codeboard app
Using the combination of shft+ctrl and typing a key does not output a capital letter anywhere.
This poses a problem when using codeboard in nano from termux.
HACKER Keyboard app lets you input capital letters in this combination.

**Comment by theintel** [comment]
Why do you need to press CTRL? Simply SHFT+letter outputs a capital letter on any terminal, including Termux.

**Comment by LordKrishna91** [comment]
using nano text editor in termux you require shft+ctrl and capital letters for specific inputs and functions

**Comment by theintel** [comment]
Didn't know that, thanks.

And looks like the dev is too occupied (with other jobs) to respond. 😉

**Comment by LordKrishna91** [comment]
No problem, the dev will update the app some time this year. 😜

**Comment by theintel** [comment]
😂

**Comment by gazlaws-dev** [comment]
Seems to be a simple fix, could you tell me an example to how you use it in nano so I can test it? 

_Sent from my Motorola Moto G (5) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LordKrishna91** [comment]
@gazlaws-dev 
opening the nano editor it displays options which require shift + ctrl + capital letters. this defeats the usage of nano with codeboard
![nano editor on termux](http://i.imgur.com/wesIGuX.png)

**Comment by gazlaws-dev** [comment]
@LordKrishna91 Can you give a specific command? like ctrl+shift+A or something. I don't use nano so I'm not familiar with the shortcuts

_Sent from my Motorola Moto G (5) using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by LordKrishna91** [comment]
@gazlaws-dev 
Sure, no problem.
  1.  To bring help:  ctrl + shift + G.
 2.  write to file:  ctrl+ shift + O.
3. to exit:  ctrl + shift + X.
4.  cut text:  ctrl + shift + K.
5. Read file:  ctrl + shift + R.
6.  Search text:  ctrl + shift + W.

**Comment by Tzuqris** [comment]
Stumbled upon this, thought I would shed some light. Those commands do NOT require the shift key. Ctrl+X is the only one that works with this keyboard. All commands work normally in Hacker's Keyboard.

**Comment by Quasic** [comment]
@Tzuqris is right. Ctrl+X works, but Ctrl+G types "g" Ctrl+J "j" etc.
