### ISSUE TITLE
Shortcut for switching keyboards

### ISSUE THREAD

**Issue by Sandmonster** [gazlaws-dev/codeboard#17]
Hello, I tried this keyboard for coding, it looks very sick, but there is really need to be a shorcut to switch keyboards e.g. to default aosp keyboard, because I can't write with this keyboard in my native language and it takes a lot of time to write smth to my friends i.e. open the app, switch the keyboard, write a message and switch the keyboard back. I can try to make this myself next few months, yet I'm very beginner in android development and appreciate if somebody would do it.

**Comment by Sandmonster** [comment]
Found out that long press space does what I wanted to.

**Comment by theintel** [comment]
But still the GLOBE button like the default android keyboard would've been faster than this long press thing. 😊
