### ISSUE TITLE
 shift lock for long all-caps words

### ISSUE THREAD

**Issue by LordKrishna91** [gazlaws-dev/codeboard#19]
This app had a shift lock for capital words. it's quite tedious to press shift + letter to output capital words like README.md, etc.

**Comment by theintel** [comment]
Yeah, there should be an option in the keyboard settings to enable/disable shift lock. 😊

**Comment by gazlaws-dev** [comment]
Long pressing the shift key will lock it, like in most keyboards. I removed the option in the settings when I added this feature since it's more intuitive.
