### ISSUE TITLE
Escape Key

### ISSUE THREAD

**Issue by lentusignavus** [gazlaws-dev/codeboard#2]
Is there a reason why the escape key was left out?

**Comment by REHAN7866** [comment]
escape key is plwced on the right side of "p" letter.....

**Comment by lentusignavus** [comment]
@REHAN7866 for me that's the backspace key. Do I have to hold it?

**Comment by rangeoshun** [comment]
+1

**Comment by REHAN7866** [comment]
Oh..sry.... That's my fault...

**Comment by dj-algorhythm** [comment]
No point in installing vim w/o ESC key.

**Comment by gazlaws-dev** [comment]
Escape Key added in latest commit (147e84c87ccca0740e25209f43d1a574a0c8dff0), should be uploaded to the PlayStore soon.
