### ISSUE TITLE
using enter to start search doesn't work

### ISSUE THREAD

**Issue by ghost** [gazlaws-dev/codeboard#20]
Using the newest version of codeboard app(4.0.3) 
enter doesn't start search on fasthub app while searching for issues  (other keyboard apps work fine like gboard)

**Comment by Bjboob14** [comment]
carltx@gmail.com

**Comment by Bjboob14** [comment]
cool

**Comment by Bjboob14** [comment]
cool

**Comment by gazlaws-dev** [comment]
Can't reproduce the bug
