### ISSUE TITLE
Enhancement: Do not output space when changing keyboard

### ISSUE THREAD

**Issue by Wolfram-Wolf** [gazlaws-dev/codeboard#25]
Long-pressing the spacebar brings up the "select input method" dialog _in addition to_ outputting a space (which is not intended). It would be better if long-pressing the spacebar only changed keyboards, without outputting a space.

**Comment by ShadyGeek** [comment]
Hello there! I'm working on a university assignment, where I must fix an issue in an existing open source programm. So, I'd like to fix this issue for you, may I?

**Comment by gazlaws-dev** [comment]
@ShadyGeek yes that would be great!

**Comment by gazlaws-dev** [comment]
Thanks @ShadyGeek for putting some love to this project 🚀

**Comment by ShadyGeek** [comment]
You've been awesome man, so helpful, thanks for the constructive criticism, it meant a lot and thank you for devoting some of your time to me. ❤️
