### ISSUE TITLE
Notification to force open keyboard

### ISSUE THREAD

**Issue by DecentGradient** [gazlaws-dev/codeboard#29]

**Comment by gazlaws-dev** [comment]
What do you mean by force open?

**Comment by DecentGradient** [comment]
Hacker keyboard has a notification option which allows you to force the
keyboard open even if the field doesn't seem to be a text field or is that
the keyboard is not opening for some reason

**Comment by gazlaws-dev** [comment]
Didn't know about that feature, thanks!
Hacker's Keyboard has an implementation here, so this a good first issue if anyone wants to contribute.

https://github.com/klausw/hackerskeyboard/blob/0394abcfe55579a94e7752a536aa41f1e8ef47eb/java/src/org/pocketworkstation/pckeyboard/NotificationReceiver.java
