### ISSUE TITLE
Feature request: Word Completion and Spell Correction

### ISSUE THREAD

**Issue by erji44** [gazlaws-dev/codeboard#32]
I just discovered codeboard on android and it looks great, crisp clean, modern, easy to use, layout is very good.
I replaced hacker's keyboard with it.
The only thing I would like to  add to codeboard is word completion and spell correction in English.
I understand this is a coder's keyboard but the layout of the keyboard is so good that can be used by normal users too not just coders.

**Comment by gazlaws-dev** [comment]
Currently in the backlog, not a high priority
