### ISSUE TITLE
 Flying key preview is pretty awful

### ISSUE THREAD

**Issue by gazlaws-dev** [gazlaws-dev/codeboard#43]
Using the default popups, it looks bad. Custom popups will take a lot more work, may also cause performance hits?

**Comment by theintel** [comment]
@gazlaws-dev But at least try to make it like the standard android keyboard popups: larger box, smaller text   and black text on white box.

![screenshot_20180705-235014](https://user-images.githubusercontent.com/12599047/42339269-07ad812e-807c-11e8-8ec7-5bd8d3807b8f.png)

**Comment by gazlaws-dev** [comment]
Duplicate of #14
