### ISSUE TITLE
With Shift, buggy Backspace 

### ISSUE THREAD

**Issue by ibnlanre** [gazlaws-dev/codeboard#52]
Backspace does not work with or after using the shift key

**Comment by Ibnlanre** [comment]
I'll probably still need a while to get used to it. But actually there's something I've been noticing recently, sometimes the backspace key works like the keyboard delete (erasing to the right), this behaviour remains until I combine the Shift and Ctrl key, to release - I'm I doing something wrong?

**Comment by theintel** [comment]
It works just fine on my Walton Primo N2 (Android 6.0). Probably its an OS related issue.
@Ibnlanre @cipharius What is the android version of your devices?

**Comment by cipharius** [comment]
My Android version is 5.1.1.

It's also worth noting that this bug doesn't happen when I'm writing in this web form. Has to be something with native text forms.

**Comment by Ibnlanre** [comment]
Mine is also 5.1
maybe that's the problem.

**Comment by theintel** [comment]
@cipharius Probably because web forms have their own text processor and don't depend on native text processor.
@Ibnlanre And it really looks like its an issue with the android 5.1.1
