### ISSUE TITLE
Backspace Button

### ISSUE THREAD

**Issue by WhoisBsa** [gazlaws-dev/codeboard#56]
I think the design of the backspace button not is cool. Maybe if you change for a normal button it would be better

**Comment by sonakollarova5** [comment]
Can I work on this issue?

**Comment by WhoisBsa** [comment]
Yes!!!

**Comment by peterekepeter** [comment]
There might be a practical solution to this, there is a symbol in unicode that was made for this 
![image](https://user-images.githubusercontent.com/7863124/67522846-295dba80-f6b6-11e9-9bed-2fbbb419d8ad.png)

**Comment by WhoisBsa** [comment]
That's what I'm Talking about!!! Good job @peterekepeter!

**Comment by peterekepeter** [comment]
@sonya323 if you come up with anything better, let me know though.

**Comment by gazlaws-dev** [comment]
Duplicate of #13
