### ISSUE TITLE
Add support for programmer Dvorak

### ISSUE THREAD

**Issue by h0cheung** [gazlaws-dev/codeboard#57]

**Comment by peterekepeter** [comment]
I've started working on it, though I'm not sure if this is how you expect it to look,

Some feedback would be nice

![image](https://user-images.githubusercontent.com/7863124/67522299-3037fd80-f6b5-11e9-96da-e3c0c3c82d8e.png)

Code: https://github.com/peterekepeter/codeboard/pull/3

**Comment by gazlaws-dev** [comment]
Closed by commit 0ad0c7949c83cd9a8d228051e32ac243e7fce5be
