### ISSUE TITLE
Feature Request : offer the project apk for download - newest version.

### ISSUE THREAD

**Issue by chagai95** [gazlaws-dev/codeboard#65]
I could create a link to Next Cloud and every once in a while we could build the apk and sync the apk (basically uploading but much easier). I have already done this with my note-taking App should not be too difficult, check out how it will look like:  [supernote.org]( supernote.org)

**Comment by chagai95** [comment]
I created an example here:
tinyurl.com/codeboard-chagai

so this is, for example, the apk of the version I modified.

**Comment by gazlaws-dev** [comment]
A cool concept, but wouldn't it be easier to fork the project, and upload an apk to your fork? Closing this as out-of-scope for now
