### ISSUE TITLE
Landscape View is broken!

### ISSUE THREAD

**Issue by peterekepeter** [gazlaws-dev/codeboard#71]
I've just started debugging the lastest master and I've noticed that landscape is completely broken, I get no keyboard at all.

    commit 4aab2de0f04f3492972830dd6bfc15d777d3ee01
    Date:   Fri May 1 12:45:12 2020 +0530

Also the separate landscape keyboard slider has been removed, was this on purpose or accident?

**Comment by peterekepeter** [comment]
@gazlaws-dev you have commented out the part which sets the landscape size, this means it stays on 0 forever and the landscape keyboard will have 0% height of the screen.

**Comment by gazlaws-dev** [comment]
Good catch! I had meant to make the landscape slider's upper/lower limit similar to how we cap the values in the potrait slider. But I never actually changed it, just commented it out. Will need to change this asap, thanks for reporting the issue.
