### ISSUE TITLE
Add QWERTZ

### ISSUE THREAD

**Issue by PandaSITT** [gazlaws-dev/codeboard#78]
Can you add the QWERTZ layout?

**Comment by peterekepeter** [comment]
should it just be a swap between Y and Z or are there supposed to be other chars as well?

**Comment by PandaSITT** [comment]
Y and Z is the important one. There are extra keys like ö, ä, ü, ß, etc.. but thy shouldn't be used when coding so they are not realy important

**Comment by peterekepeter** [comment]
It looks like there is already a pull request for this https://github.com/gazlaws-dev/codeboard/pull/76

**Comment by PandaSITT** [comment]
#
