### ISSUE TITLE
Different arrow keys

### ISSUE THREAD

**Issue by pudah** [gazlaws-dev/codeboard#83]
I recently got a new device and have a problem now that I have installed CodeBoard on it.

The left and right arrow keys look different from the up and down arrows. 

The problem happens with both version 4.x and 5.x of CodeBoard.

I am not sure if it is the Android version or the manufacturer skin that is causing the problem.

Old device is an NVIDIA Shield Tablet K1 running Android 7
New device is a Samsung Galaxy Tab S6 Lite running Android 10 and OneUI 2.5

Here are a couple of screen shots to illustrate the difference:

old device: https://i.imgur.com/Cx1S8TK.png
new device: https://i.imgur.com/veInHg1.png

Is this something that can be fixed?

For the record, the plain dark old style arrows are preferred over the fancy blue ones that are showing in the new screen shot.

**Comment by peterekepeter** [comment]
Code board relies on Android to all the keys you see with the default font instead of supplying it's own vector icons. Your new device simply decided to replace the arrows with emojis.

Hmmm, maybe it would be best to supply custom icons for some of these keys just to ensure consistent experience across all devices. What do you think @gazlaws-dev ?

**Comment by pudah** [comment]
Just popping in to see if any thought has been given to making a change to the arrows. I've been using my new device more and more and the finding the inconsistent arrows rather distracting.

**Comment by gazlaws-dev** [comment]
Hi @pudah, it's been a while since I updated this app. I've added this change to the repository, but I've not pushed the change to the Play Store yet. If you want, here's an apk with the icons fixed:  
[app-debug.zip](https://github.com/gazlaws-dev/codeboard/files/6370313/app-debug.zip)

**Comment by gazlaws-dev** [comment]
Closed by commit 9019517de1c7ebabb37d06f072dfa6996cd607f4

**Comment by pudah** [comment]
I missed your message here but did notice an update from the play store. Thanks very much for this change!
