### ISSUE TITLE
draw behind navigation bar

### ISSUE THREAD

**Issue by n-ce** [gazlaws-dev/codeboard#84]
keyboard theme and navigation bar does not match

**Comment by peterekepeter** [comment]
I think I know what you mean. My phone has a black navigation bar so I'm using the black theme. But this is just a coincidence, that both navigation bar and keyboard happen to have the same color.

Related: https://github.com/gazlaws-dev/codeboard/issues/80 

But this could be solved by having user defined themes, though that would be a huge new feature.

**Comment by n-ce** [comment]
I'm using v6 but it didn't work. The navbar never changes color.
![Screenshot_20210525-083642](https://user-images.githubusercontent.com/69345507/119433712-68da0600-bd34-11eb-9079-2986cf162434.png)
For reference, I also use AnySoftKeyboard which can do this. 
 @![Screenshot_20210525-083820](https://user-images.githubusercontent.com/69345507/119433794-94f58700-bd34-11eb-91c6-a5722974df9d.png)
@peterekepeter
