### ISSUE TITLE
Allow to have arrow keys and cut/copy/paste buttons at the same time

### ISSUE THREAD

**Issue by tambapps** [gazlaws-dev/codeboard#95]
Hello, I'll start by sayingthanks for this awesome app, it is really useful to me.

I prefered a previous version of this app where it was possible to have arrow keys on the top of the keyboard, and have copy/paste buttons. If I remember correctly I think they were where are the Fn (F1, F2, ...) buttons now.

I saw that there is an option `Replace arrows with cut/copy/paste buttons` but I regularly use arrows and cut/copy/paste. Could you give the possibility to have them both please?
For example, could you add an option to replace Fn buttons with cut/copy/paste buttons?

**Comment by gazlaws-dev** [comment]
How about the cut/copy/paste buttons in the new Clipboard section? Pressing Ctrl changes the  "SYM" buttom to a "CLIP" button, so when you click Ctrl, then CLIP, you'll see the cut/copy/paste buttons. Let me know if that works for you.


https://user-images.githubusercontent.com/19718602/127731334-ee2f9626-0be6-4e1b-9d97-53995de78bd1.mp4

**Comment by tambapps** [comment]
Oh, cool! I didn't notice the CLIP button, sorry

Yes this is perfect, thanks!
